# Only 3 modes are useful on a single 16:10 screen
layouts:
  - tall
  - fullscreen
  - wide

mouse-follows-focus: true
focus-follows-mouse: false

screen-padding-left: 5
screen-padding-right: 5
screen-padding-top: 5
screen-padding-bottom: 5

# Add 5 margin between windows
window-margins: true
window-margin-size: 5
